---
title: "Matemática Atuarial I"
---

- ## __Sobre o Curso:__

O presente site foi elaborado pelo disciente Nadson Angelo Silva Nogueira para a disciplina de Matemática Atuarial I, a partir do conteúdo elaborado pela Dra. Luana Junqueira Dias Myrrha, professora adjunta do Departamento de Demografia e Ciências Atuariais (DDCA) da Universidade Federal do Rio Grande do Norte (UFRN), em conjunto com demais colegas professores de atuária de outras instituições brasileiras. Destaca-se aqui o nome do Dr. Renato Assunção, professor do Departamento de Ciência da Computação da Universidade Federal de Minas Gerais (UFMG), quem inicou a contrução deste material no curso de Ciências Atuariais da UFMG.  

Este material serve de apoio aos alunos que estão cursando a disciplina de Matemática Atuarial I, pois contém as explicações das formúluas utilizadas na disciplina e exemplos resolvidos manualmente e utilizando a linguagem R.

O conteúdo da disciplina irá abordar conceitos básicos, como:

  - __Seguros de vida pagos no momento de morte (tempo contínuo e discreto)__
   
    - Seguro de vida temporário de n-anos
   
    - Seguro de vida inteira
   
    - Seguro Dotal puro de n-anos
   
    - Seguro Dotal Misto
   
    - Seguro de Capital Diferido
    
  - __Anuidades ou séries financeiras__
  
  - __Anuidades atuariais (discretas e contínuas)__
  
    - Anuidades Vitalícias (contínua)
  
    - Valor Presente Atuarial (contínua)
  
    - Anuidades temporárias (contínua)
  
    - Anuidade Vitalícia Diferida de m anos (contínua)
  
    - Anuidade Vitalícia com Pagamentos Certos para os Primeiros m anos (contínua)
  
    - Anuidade Antecipada (discreta)
  
  - __Prêmios e benefícios__
  
  - __Prêmios carregados__
  
    - Prêmio de inventário
  
    - Prêmio Zilmerado (Zilmer, 1863)
  
    - Prêmio comercial (ou de tarifa)
    
### Exposto os conteúdos abordados pelo curso, é importante que o aluno tenha conhecimentos sobre as seguintes áreas:

  - __Cálculo Diferencial e Integral I__
  
  - __Probabilidade e Estatística__

- __Matemática Financeira__
  
    - Juros e inflação
    
    - Valor futuro e valor presente
    
    - Vendas parceladas
    
    - Formas de amortização
  
  - __Funções de tabelas de sobrevivência (Tábuas de vida ou morte)__
  

    
    
