---
title: "Matemática Atuarial"
---

- __O que é:__

Conhecida também como matemática dos seguros, a matemática atuarial trabalha com cálculos para avaliar riscos e sistemas de investimento de seguro. Criada através da probabilidade para jogos (teoria dos jogos), no século XVII, na europa, seu susgimento está vinculado a necessidade de ter um sistema capaz de responder questões referentes ao funcionamento dos sistemas de seguro e previdência com o desenvolvimento da sociedade.

- __Ciências Atuariais:__

O nome da profissão pode soar estranho para muita gente, mas a maioria provavelmente já usufrui ou ainda vai depender de seus serviços.

As Ciências Atuariais (Atuária) é a ciência que analisa e gerencia riscos e expectativas de quaisquer naturezas: econômicas, financeiras e biométricas, com o objetivo de prover proteção social. Para isso, as metodologias mais tradicionais são baseadas em teorias econômicas, modelos matemáticos, probabilísticos e estatísticos com o objetivo de descrever e representar fenômenos dotados de incerteza a respeito de suas causas, realizações e impactos. Portanto, a Atuária é uma área de conhecimento multidisciplinar.

Embora suas origens tenham raízes na Roma antiga, as ciências atuariais surgiram formalmente na Inglaterra no século XIX, estudando os padrões de mortalidade da população e seus principais desdobramentos: cálculos da expectativa de vida, com interesse em aposentadorias e pensões.